# Generated by Django 5.0.2 on 2024-02-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('p1_score', models.PositiveIntegerField()),
                ('p2_score', models.PositiveIntegerField()),
                ('winner', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
