# Generated by Django 5.0.3 on 2024-03-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_player1_alter_game_player2'),
        ('user', '0004_profile_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game1', to='games.game')),
                ('game2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game2', to='games.game')),
                ('game3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game3', to='games.game')),
                ('players', models.ManyToManyField(related_name='tournaments', to='user.profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
