# Generated by Django 5.0.3 on 2024-03-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
