# Generated by Django 5.0.3 on 2024-03-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_friendrequest_friendrequest_unique_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(null=True),
        ),
    ]
