# Generated by Django 5.0.3 on 2024-03-24 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_tournament_players_tournament_name'),
        ('user', '0004_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='games.tournament'),
        ),
        migrations.CreateModel(
            name='GameInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room_name', models.CharField(max_length=255)),
                ('from_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_invites_sent', to='user.profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_invites_received', to='user.profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddConstraint(
            model_name='gameinvite',
            constraint=models.UniqueConstraint(fields=('from_user_id', 'to_user'), name='unique_game_invite'),
        ),
    ]
