# Generated by Django 5.0.3 on 2024-03-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_tournament_gameinvite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinvite',
            name='room_name',
        ),
    ]
