# Generated by Django 5.0.3 on 2024-03-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_gameinvite_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvite',
            name='from_user',
            field=models.CharField(default='dsas', max_length=255),
            preserve_default=False,
        ),
    ]
